# Generated by Django 2.2.6 on 2019-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20191026_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
